apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ux-github-actions
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ux-github-actions
    app.kubernetes.io/part-of: ux-github-actions
  name: ux-github-actions
  namespace: ux-github-actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ux-github-actions
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ux-github-actions
    spec:
      containers:
      - image: quay.io/jduimovich0/ux-github-actions:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
status: {}
