apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ux-github-actions
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ux-github-actions
    app.kubernetes.io/part-of: ux-github-actions
  name: ux-github-actions
  namespace: ux-github-actions
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ux-github-actions
    weight: 100
status: {}
